<?php
// ไฟล์ติดตั้งระบบ WMS อัตโนมัติ
error_reporting(E_ALL);
ini_set('display_errors', 1);

echo "<h1>🚀 ติดตั้งระบบ WMS - Austam Good</h1>";

// ตรวจสอบว่ามีการ submit form หรือไม่
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host = $_POST['host'] ?? 'localhost';
    $port = $_POST['port'] ?? '3306';
    $user = $_POST['user'] ?? 'root';
    $pass = $_POST['pass'] ?? '';
    
    echo "<h2>🔧 กำลังติดตั้ง...</h2>";
    
    try {
        // ทดสอบการเชื่อมต่อ
        $dsn = "mysql:host={$host};port={$port};charset=utf8mb4";
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);
        
        echo "✅ เชื่อมต่อ MySQL สำเร็จ<br>";
        
        // สร้างฐานข้อมูล
        $pdo->exec("CREATE DATABASE IF NOT EXISTS wms_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        echo "✅ สร้างฐานข้อมูล wms_system สำเร็จ<br>";
        
        // เลือกฐานข้อมูล
        $pdo->exec("USE wms_system");
        
        // อ่านไฟล์ SQL
        $sql_file = __DIR__ . '/database_schema.sql';
        if (file_exists($sql_file)) {
            $sql_content = file_get_contents($sql_file);
            
            // แยก SQL statements
            $statements = array_filter(
                array_map('trim', explode(';', $sql_content)),
                function($statement) {
                    return !empty($statement) && !preg_match('/^\s*--/', $statement);
                }
            );
            
            $success_count = 0;
            foreach ($statements as $statement) {
                try {
                    $pdo->exec($statement);
                    $success_count++;
                } catch (PDOException $e) {
                    // ข้าม error ที่ไม่สำคัญ เช่น table already exists
                    if (strpos($e->getMessage(), 'already exists') === false) {
                        echo "⚠️ Warning: " . $e->getMessage() . "<br>";
                    }
                }
            }
            
            echo "✅ Import ตาราง {$success_count} statements สำเร็จ<br>";
        } else {
            echo "❌ ไม่พบไฟล์ database_schema.sql<br>";
        }
        
        // อัปเดตไฟล์ config
        $new_config = "<?php
// Database configuration - Auto-generated by setup.php
define('DB_HOST', '{$host}');
define('DB_PORT', '{$port}');
define('DB_NAME', 'wms_system');
define('DB_USER', '{$user}');
define('DB_PASS', '{$pass}');
define('DB_CHARSET', 'utf8mb4');

// Timezone
date_default_timezone_set('Asia/Bangkok');

// Error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);
?>";
        
        file_put_contents(__DIR__ . '/config/database.php', $new_config);
        echo "✅ อัปเดตไฟล์ config/database.php สำเร็จ<br>";
        
        // ทดสอบการ login
        $pdo->exec("USE wms_system");
        $stmt = $pdo->query("SELECT COUNT(*) FROM manage_user");
        $user_count = $stmt->fetchColumn();
        
        echo "<div style='background: #d4edda; padding: 15px; border-radius: 5px; margin: 20px 0;'>";
        echo "<h3>🎉 ติดตั้งสำเร็จ!</h3>";
        echo "<p><strong>ฐานข้อมูล:</strong> wms_system</p>";
        echo "<p><strong>ผู้ใช้งาน:</strong> {$user_count} คน</p>";
        echo "<p><strong>การตั้งค่า:</strong> {$host}:{$port}</p>";
        echo "</div>";
        
        echo "<h3>🔑 บัญชีทดสอบ:</h3>";
        echo "<div style='background: #f8f9fa; padding: 15px; border-radius: 5px;'>";
        echo "<p><strong>Admin:</strong> ADMIN001 / password</p>";
        echo "<p><strong>พนักงาน:</strong> WH001 / password</p>";
        echo "<p><strong>สำนักงาน:</strong> OFFICE001 / password</p>";
        echo "</div>";
        
        echo "<p style='margin-top: 20px;'>";
        echo "<a href='login.php' style='background: #007bff; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;'>🚀 เข้าใช้งานระบบ</a>";
        echo "</p>";
        
    } catch (PDOException $e) {
        echo "<div style='background: #f8d7da; padding: 15px; border-radius: 5px; color: #721c24;'>";
        echo "<h3>❌ เกิดข้อผิดพลาด</h3>";
        echo "<p>" . htmlspecialchars($e->getMessage()) . "</p>";
        echo "</div>";
        
        // แสดงฟอร์มอีกครั้ง
        $show_form = true;
    }
} else {
    $show_form = true;
}

if (isset($show_form) && $show_form): ?>

<h2>📝 กรอกข้อมูลการเชื่อมต่อ MySQL</h2>

<form method="POST" style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
    <div style="margin-bottom: 15px;">
        <label for="host" style="display: block; margin-bottom: 5px; font-weight: bold;">Host:</label>
        <input type="text" id="host" name="host" value="localhost" required 
               style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
    </div>
    
    <div style="margin-bottom: 15px;">
        <label for="port" style="display: block; margin-bottom: 5px; font-weight: bold;">Port:</label>
        <select id="port" name="port" style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
            <option value="3306">3306 (MySQL มาตรฐาน)</option>
            <option value="3307">3307 (XAMPP Alternative)</option>
        </select>
    </div>
    
    <div style="margin-bottom: 15px;">
        <label for="user" style="display: block; margin-bottom: 5px; font-weight: bold;">Username:</label>
        <input type="text" id="user" name="user" value="root" required 
               style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
    </div>
    
    <div style="margin-bottom: 15px;">
        <label for="pass" style="display: block; margin-bottom: 5px; font-weight: bold;">Password:</label>
        <input type="password" id="pass" name="pass" value="" 
               style="width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;">
        <small style="color: #666;">ปกติ XAMPP ไม่มี password (ว่างเปล่า)</small>
    </div>
    
    <button type="submit" style="background: #28a745; color: white; padding: 12px 24px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;">
        🚀 ติดตั้งระบบ
    </button>
</form>

<div style="background: #fff3cd; padding: 15px; border-radius: 5px; margin-top: 20px;">
    <h3>💡 คำแนะนำ:</h3>
    <ul>
        <li>ตรวจสอบว่า MySQL service ทำงานอยู่</li>
        <li>ลองทั้ง port 3306 และ 3307</li>
        <li>XAMPP ปกติใช้ root โดยไม่มี password</li>
    </ul>
</div>

<?php endif; ?>

<hr style="margin: 30px 0;">
<p style="text-align: center; color: #666;">
    <a href="test_connection.php">🔧 ทดสอบการเชื่อมต่อ</a> | 
    <a href="index.php">🏠 หน้าหลัก</a>
</p>

<style>
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    max-width: 800px;
    margin: 20px auto;
    padding: 20px;
    background: #f8f9fa;
    line-height: 1.6;
}

h1, h2, h3 {
    color: #333;
}

h1 {
    border-bottom: 3px solid #007bff;
    padding-bottom: 10px;
}

a {
    color: #007bff;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

input:focus, select:focus {
    outline: none;
    border-color: #007bff;
    box-shadow: 0 0 5px rgba(0,123,255,0.3);
}

button:hover {
    background: #218838 !important;
}
</style>