<?php
// Database configuration - Auto-generated by setup.php
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'wms_system');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');

// Timezone
date_default_timezone_set('Asia/Bangkok');

// Error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);
?>